### ISSUE TITLE
 Multipart Copy Range Support

### ISSUE THREAD

**Issue by simon-mo** [skyplane-project/skystore#25]
Currently, Docker registry tries to use range copy to build up the object. But without UploadPartCopy with a CopySourceRange, the end object is replicated multiple times. Currently we have a workaround by setting Registry's threshold to few Gs but this is not scalable.

**Comment by simon-mo** [comment]
For Azure and GCP, since we are going to work using "multipart" API anyway, we might as well perform the Copy in parallel if the item is too large. This is an item for future optimization.

**Comment by lynnliu030** [comment]
So to add CopySourceRange support to `upload_part_copy` function implemented in skyproxy.rs now, what we need to do is to change the GCP and Azure client-side implementations, right? Also not sure if I understand this entirely, wdym by copy in parallel? 

> For Azure and GCP, since we are going to work using "multipart" API anyway, we might as well perform the Copy in parallel if the item is too large. This is an item for future optimization.

**Comment by simon-mo** [comment]
Correct. UploadPartCopy with CopySourceRange is required for container
workload. I didn't get to implement it in time and used some hacky
workaround. 

I believe both operations are supported in GCP and Azure (this can be a
good starter task!). 

Copy in parallel means breaking up the a large part into smaller parts
so they can be copied concurrently. This depends on whether
CopyObject/CopyPart is an O(1) or O(n) operation (investigation of this
can also be a good starter task).
