### ISSUE TITLE
CLI support 

### ISSUE THREAD

**Issue by lynnliu030** [skyplane-project/skystore#28]
Support CLI functionalities including 
* Initialization: `skystore init --config` start s3 proxy and store server, and initialize necessary credentials 
* Register: `skystore register --config` register existing buckets / objects to skystore with a config file 
* Warmup: `skystore warmup --bucket --key --regions` warmup a particular objects in the set of regions 

[Example](https://github.com/skyplane-project/skystore/tree/bucket-op/s3-proxy/test) init and register config for now

**Comment by sarahwooders** [comment]
## Initiating and Configuring Sky Storage 

We can assume that the user runs `skyplane init` to save all their credentials. 

1. Instantiate the bucket with a `CONFIG_FILE` which contains JSON (TODO: insert example)  
```
ss init --config <CONFIG_FILE> 
```

2. Create the bucket with `start`, which creates the proxy and server  
```
ss start 
```
This will return a endpoint, `SKY_STORAGE_ENDPOINT` to make queries against. 
3. Stop the proxy/server with `ss stop` 
5. Edit the configuration by running: 
```
ss apply --config <CONFIG_FILE> 
```

## Working with Buckets in Sky Storage 
1. Creating a bucket / other bucket operations (upload, read, etc.) 
```
awscli [OPERATION] --endpoint-url <SKY_STORAGE_ENDPOINT> 
```

2. Warming up data in region manually  
```
ss warmup --bucket  <BUCKET NAME> --key <KEY> --regions <REGION1 REGION2 ... >  
```
