### ISSUE TITLE
Clean up metadata entries upon timeout 

### ISSUE THREAD

**Issue by lynnliu030** [skyplane-project/skystore#30]
In SkyStore Server code, it is possible that metadata lock never gets released (i.e. always in `pending` status or `pending_delete` status). Check out how upload is done via two-phase commit protocol [here](https://github.com/skyplane-project/skystore/blob/main/store-server/app.py#L716-L904). 

We need to track the time of lock, set a timeout (i.e. 10 mins), and release such lock by setting the status to `ready`. 

For example, in SkyStore server, we can do the following for Object 

- [x] Keep track of how long `pending` or `pending_delete` is set for each PhysicalObject 
- [x] SkyStore server periodically scans and resets status to `ready` for these PhysicalObjects 
- [x] If all PhysicalObject is set to `ready`, then revert LogicalObject back to `ready` state 

We need to write test case in SkyStore server side in `skystore-server/test_app.py`, also need to extend this to Bucket lock as well (i.e. during create or delete). 

Note: in the future, might want to initiate some sort of reconciliation process, querying state of data plane to understand what actually happened before reset metadata lock.

**Comment by HenricZh** [comment]
PR: https://github.com/skyplane-project/skystore/pull/44
