### ISSUE TITLE
Implement write back to local store (a.k.a lazy pull) for Proxy

### ISSUE THREAD

**Issue by simon-mo** [skyplane-project/skystore#9]
Currently write back (lazy pull) is implemented, but needs a better way of invocation

**Comment by sarahwooders** [comment]
Can we elaborate?

**Comment by simon-mo** [comment]
Originally, the idea is when an object is retrieved in a secondary region, instead of just sending the data directly back to the client, also write the data into the secondary region proxy is serving from. But it seems @lynnliu030 implemented it already?
